#! /bin/sh
# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/Downloads/images.jpg &
xrandr --output DP-2-2 --primary --mode 1920x1080 --output eDP-1 --off  &
#Workspaces
picom &
bash ~/.config/polybar/launch.sh &
bspc monitor DP-2-2 -d 1 2 3 4 5
bspc config border_width 0
bspc config window_gap 25
bspc config split_ratio 0.53
